host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pipenv

managers:
  - name: info
  - name: version
    configuration:
      maintainers:
        - LaVLaS
        - maroroman
        - crobby
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
